# Generated by Django 4.0.4 on 2022-07-29 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address_2',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
