# Generated by Django 4.0.4 on 2022-08-30 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authenticate', '0003_alter_response_category_alter_user_first_name_and_more'),
        ('authenticate', '0003_alter_response_category_emailverification'),
    ]

    operations = [
    ]
